-- MySQL Script generated by MySQL Workbench
-- Fri Sep 25 22:53:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_empresa
-- -----------------------------------------------------
-- Database encarregada de simular uma empresa e gerenciar os dados da mesma.
-- 
-- Data de criação: 22/09/2020
-- Última alteração: 25/09/2020

-- -----------------------------------------------------
-- Schema bd_empresa
--
-- Database encarregada de simular uma empresa e gerenciar os dados da mesma.
-- 
-- Data de criação: 22/09/2020
-- Última alteração: 25/09/2020
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_empresa` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `bd_empresa` ;

-- -----------------------------------------------------
-- Table `bd_empresa`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_empresa`.`fornecedores` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'Campo de armazenamento do número de identificação do fornecedor',
  `name` VARCHAR(45) NOT NULL COMMENT 'Campo de armazenamento do nome do fornecedor',
  `email` VARCHAR(60) NOT NULL COMMENT 'Campo de armazenamento do email do fornecedor',
  `comment` TEXT NOT NULL COMMENT 'Campo de armazenamento de comentários sobre o fornecedor',
  `cnpj` VARCHAR(18) NOT NULL COMMENT 'Campo de armazenamento do CNPJ do fornecedor',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'A tabela tem o objetivo de armazenar todos os dados relacionados aos fornecedores da empresa';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
